import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import Upload from '../components/Upload'
import TranscriptText from '../components/TranscriptText'
import Query from '../components/Query'
import { useState } from 'react'
import Scrape from '../components/Scrape'
import PodcastItem from '../components/PodcastItem'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const [text, setText] = useState('')
  return (
    <>
      <Head>
        <title>Info Insighters</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>

        <div className="container mx-auto flex flex-col items-center px-4 py-16 text-center md:py-8 md:px-10 lg:px-32 xl:max-w-3xl">
          <h1 className="font-extrabold text-transparent text-6xl bg-clip-text bg-gradient-to-r from-green-200 to-green-600">Info Insighters
          </h1>
          <p className="px-8 mt-8 mb-12 text-2xl">Amazing Podcast Searching Platform</p>
          <div className="flex  justify-center space-x-3">
            <div className="w-1/2 rounded-md shadow-md bg-gray-50 text-gray-800">
              <img src="https://lexica-serve-encoded-images2.sharif.workers.dev/md/e6a49bc4-1165-4241-8a42-eb3c218cbe60" alt="" className="object-cover object-center w-full rounded-t-md h-72 bg-gray-500" />
              <div className="flex flex-col justify-between p-6 space-y-8">
                <div className="space-y-2">
                  <h2 className="text-3xl font-semibold tracking-wide">Episode recommend</h2>
                  <p className="text-gray-800">Search for a topic you are interested in </p>
                </div>
                <Link href="/Episode" className='className="flex items-center justify-center w-full p-3 font-semibold tracking-wide rounded-md bg-green-600 text-gray-50'>Try now</Link>
              </div>
            </div>
            <div className="w-1/2 rounded-md shadow-md bg-gray-50 text-gray-800">
              <img src="https://lexica-serve-encoded-images2.sharif.workers.dev/md/2740cebd-586d-4c0e-8ebf-6358864af909" alt="" className="object-cover object-center w-full rounded-t-md h-72 bg-gray-500" />
              <div className="flex flex-col justify-between p-6 space-y-8">
                <div className="space-y-2">
                  <h2 className="text-3xl font-semibold tracking-wide">Segment Summarize</h2>
                  <p className="text-gray-800">query the associated segment and summarise it</p>
                </div>

                <Link href="/Summarize" className='className="flex items-center justify-center w-full p-3 font-semibold tracking-wide rounded-md bg-green-600 text-gray-50'>Try now</Link>
              </div>
            </div>

          </div>
        </div>
        {/* <Upload setText={setText} /> */}
        {/* <TranscriptText text={text} /> */}

      </main>
    </>
  )
}
